### PR TITLE
COPYING -> LICENSE

### PR DESCRIPTION
**Pull request by cvvergara**
Fixes name of the file of the license

@pgRouting/admins

### CODE REVIEW

**Comment by dkastl** [comment]
I think `COPYING` is a common file name to place the license text.
But honestly I can't proof that.

Well, just checked Gitlab and its proposed name when adding the license, and it's by default `LICENSE`.

**Comment by cvvergara** [comment]
Well, I am making this pull request based on the we are the example of what not to do:
https://lists.osgeo.org/pipermail/incubator/2017-April/003242.html

**Comment by dkastl** [comment]
OK, you won! ;-)

**Comment by cvvergara** [comment]
@dkastl 
based on the mail link above, I think that this issue can be closed: #124 
If that is the case, lets change the milestone to 2.5 (not planning to make a 2.4.1) before closing.

**Comment by dkastl** [comment]
Agreed.

**Pull request merged**
