### PR TITLE
Contraction 2.2

### PR DESCRIPTION
**Pull request by cvvergara**
Merging contraction Hierarchies code from Rohtih

### CODE REVIEW

**Comment by woodbri** [comment]
Looks like the directory structure needs a little clean up:
```
[contraction-2.2.0] ~/work/pgrouting$ find src/contraction/ -type d
src/contraction/
src/contraction/qgis
src/contraction/test
src/contraction/sql
src/contraction/osm
src/contraction/src
src/contraction/src/cmake
src/contraction/src/sql
src/contraction/src/src
src/contraction/src/src/contraction
src/contraction/src/src/contraction/doc
src/contraction/src/src/contraction/sql
src/contraction/src/src/contraction/src
src/contraction/src/src/contraction/src/tester
src/contraction/src/src/myastar
src/contraction/src/src/myastar/sql
src/contraction/src/src/myastar/src
src/contraction/src/src/mydijkstra
src/contraction/src/src/mydijkstra/sql
src/contraction/src/src/mydijkstra/tester
src/contraction/src/src/mydijkstra/src
src/contraction/src/src/common
src/contraction/src/src/common/src
```
Notice the ``.../src/src/...`` above.

Also I noticed that there appear to be some executable files checked in.
```
[contraction-2.2.0] ~/work/pgrouting$ find src/contraction/ -executable -a -not -type d
src/contraction/osm/berlin_test_2.osm
src/contraction/src/src/contraction/src/using_Graphmin
src/contraction/src/src/contraction/src/tester/berlin.txt
src/contraction/src/src/contraction/src/tester/contracted_ways_0.txt
src/contraction/src/src/mydijkstra/src/using_CHdijkstra
src/contraction/src/src/common/src/using_myGraph
```
you can ``chmod -x *.txt`` to clean up the text files.

**Comment by cvvergara** [comment]
@woodbri 
I like the "little"  but first things first, have the code in the repo.
The clean up is going to be done gradually as we integrate it to pgRouting.

**Comment by dkastl** [comment]
Well, just make sure, that accidentally committed don't remain in history, especially if they are of significant size. It's a weak point of Git, that repositories can grow pretty big.

**Comment by cvvergara** [comment]
@dkastl 
We need to delete files gradually, right now its preety big.

**Pull request merged**
