### PR TITLE
Removing CGAL

### PR DESCRIPTION
**Pull request by cvvergara**
This PR removes CGAL, GMP and MTFR dependencies.

For that purpose, the underlying code for the alpha shape algorithm had to be written to fulfill pgrouting way of using CGAL's alphashape.

Note that an alpha shape consists on a collection of polygons, lines and points, but pgRouting has being using only the polygons. So the algorithm implemented in this PR ignores lines and points that are part of an alpha shape, just as the lines and points were ignored from CGAL results.

The [pgr_alphaShape](http://docs.pgrouting.org/2.6/en/pgr_alphaShape.html) is useless by itself (its the "core" function), unless its being used using [pgr_pointsAsPolygons](http://docs.pgrouting.org/2.6/en/pgr_pointsAsPolygon.html) which converts the output of pgr_alphaShape to polygon geometries.

The implementation this PR is proposing: 
- currently named pgr_alphaShape1 (see TODO)
- receives as input an array of geometries
  -  can be geometry collections, polygons, lines, points
- output a MUTIPOLYGON, or GEOMETRYCOLLECTION EMPTY when no polygon is found
- The parameter "alpha" in CGAL is the square of the spoon radius VS in this implementation the parameter is the spoon radius. (see TODO)
- The algorithm implemented is based on Delauny Triangles that are calculated using PostGIS [ST_DelaunyTriangles](https://postgis.net/docs/ST_DelaunayTriangles.html), The Triangle Area is accepted as part of the alpha shape result when the triangles circumcenter's radius `r` < `spoon radius`.
- This implementation was tested against the current results returned with [CGAL]
  (https://github.com/cvvergara/pgrouting/blob/a4f91e45311b5df760ed3fa887610384b4dcae78/tools/testers/alphaShapeTester.sql#L49)
  - on the [sample data](https://github.com/cvvergara/pgrouting/blob/a4f91e45311b5df760ed3fa887610384b4dcae78/pgtap/alpha_shape/sample.sql)
  - on an [`S` shape](https://github.com/cvvergara/pgrouting/blob/a4f91e45311b5df760ed3fa887610384b4dcae78/pgtap/alpha_shape/s-shape.sql)
  - on an [additional example](https://github.com/cvvergara/pgrouting/blob/a4f91e45311b5df760ed3fa887610384b4dcae78/pgtap/alpha_shape/notebook-shape.sql)
  - Once the  comparison passed, the wrappers were written, and the wrappers pass the tests

## TODO
Keep in mind that pgRouting focus is not on geometries, so once PostGIS has an alpha shape function, say `ST_AlphaShape`, that returns a geometry collection of polygons lines and points, then this "specialization" will be just a wrapper of such a function that extracts the polygon part.

### Give an appropriate name to this function

- pgr_alphaShape:
    - **pgr** gives an idea that is not an  `ST_AlphaShape`
    - **alphaShape** its not returning the complete alpha shape, only the polygon part of the alpha shape, so its not really the alpha shape but gives an idea that is an specialization of the alpha shape.
    - rename the parameter: instead of alpha, use spoon radius, also gives the idea that is not THE alpha shape.

- pgr_pointsAsPolygons:
    -  **points**:  Consider that it receives geometries, not only points in the form id, x, y
    -  **AsPolygon**: a polygon could be the convex hull, the concave Hull, the polygon part of an alphaShape.

### Move to legacy pgr_alphaShape & pgr_pointsAsPolygons
- pgr_pointsAsPolygons & pgr_alphaShape have being rewritten as wrappers of the new implemented function, and the wrappers have being tested.
- move the wrappers to legacy.
- remove the tests that compare old code with new code

### Documentation
- update the documentation appropriately

@pgRouting/admins

### CODE REVIEW

**Comment by robe2** [comment]
Probably more appropriate to return a MULTIPOLYGON EMPTY rather than GEOMETRYCOLLECTION EMPTY

**Comment by sanak** [comment]
I have not tested it on my local environment yet, but from the description, I think that it is great improvement. 👍 

From my side, if current listed sample data doesn't include hole polygon case (like https://github.com/pgRouting/pgrouting/issues/235#issuecomment-35805805), adding hole polygons case sample is preferable.
(Although, adjusting spoon radius value can generate hole polygons from other sample data.)

Also, performance comparison between old and new implementation with big (real) data is preferable.

**Comment by cvvergara** [comment]
It does generate polygons with holes

**Comment by cvvergara** [comment]
Some numbers
libpgrouting.so size is around 2000000 less
I don't know about performance, that I would care when postGIS implements it.
What I do know is that for small alpha values sometimes the function points as polygon returned NULL
when there was a polygon, that is somehow the driver code was catching loose lines that could not be made as polygons so it returned NULL.

**Comment by cvvergara** [comment]
I will proceed on removing the old signatures and name the function pgr_alphaShape and documenting

**Comment by cayetanobv** [comment]
@cvvergara @dkastl I have to remove CGAL from docker-pgrouting v3 (docker image will be light :) and this is great!). I'm going to open the issue to remember it.

**Comment by cvvergara** [comment]
@cayetanobv  this PR I think is ready for merge, how can we work it out:
- I do the merge then you do the change in docker and I fix later on other PR  if something is worng
@robe2 
- I do the merge then adjust debbie, jenkins, bessie to not compile with CGAL, we can fix on other PR any adjustments needed for the builds

**Comment by cayetanobv** [comment]
@cvvergara when you merge this PR I will merge this: https://github.com/pgRouting/docker-pgrouting/pull/9
Could you review it?

**Pull request merged**
