### PR TITLE
[alpha_shape] fixing PLSQL

### LINKED ISSUE #2122: Fix Codacy: alpha_shape
instructions on #2120

### PR DESCRIPTION
**Pull request by bkrit**
Fixes #2122 

Changes proposed in this pull request:
- changed the sql and result files to fix the codacy PLSQL errors/warnings

@pgRouting/admins

### CODE REVIEW

**Comment by dkastl** [comment]
Thanks for your help to improve pgRouting! But what is the purpose of this change? `--` is a common way to comment lines in plpsql.

**Comment by bkrit** [comment]
> Thanks for your help to improve pgRouting! But what is the purpose of this change? `--` is a common way to comment lines in plpsql.

This change has been done to fix the codacy PLSQL errors/warnings as mentioned in #2120

**Comment by dkastl** [comment]
Oh, I see. Thanks for referring to the issue.

**Review by cvvergara — APPROVED** [review]
Thanks for the contribution to pgRouting

**Pull request merged**
