### PR TITLE
Actions more tests no travis

### LINKED ISSUE #1415: Stop using travis for CI and move to actions
From #1335 conversation

travis-ci is very limited in concurrent processes max 5

To remove travis as our main CI and use (github actions)[https://docs.github.com/en/actions]
- builds have to be made on actions
- documentation has to be build on actions
- documentation tests have to be tested on actions
- some file checking that is done on travis has to be made on actions mainly
  - check the NEWS is up to date
  - check the signatures file are OK

### PR DESCRIPTION
**Pull request by cvvergara**
Fixes #1415  .

Changes proposed in this pull request:
- New actions CI files
  -  check files that need to be up to date
  -  check queries results
This tests are not necessary to do on branches that come from transifex.

@pgRouting/admins

### CODE REVIEW

**Comment by dkastl** [comment]
Just as a side note: I receive lots of Appveyor notifications for the Transifex updates. Is this just me?

**Comment by cvvergara** [comment]
@dkastl I also have a lot, because I still use appveyor to test visual studio, my messages loo like
```
Build pgrouting 2.6.3048 completed

Commit 2b3e8df486 by cvvergara on 7/10/2020 4:45 PM:
[actions] check signature files 
```

**Comment by dkastl** [comment]
I see, so this is just about Travis.
Hopefully we can get rid of Appveyer as well in the future

**Comment by cvvergara** [comment]
well, we don't officially use appveyor officialy in the main repository, the app is been cancelled for pgRouting organization.
But I will stop using it once in actions I can test visual studio

**Comment by cvvergara** [comment]
There is something wrong it should be building for ubuntu

**Comment by cvvergara** [comment]
ok now ubuntu is also checked on non transifex pull_request

**Pull request merged**
