### PR TITLE
Add newly created images and remove the previous ones

### PR DESCRIPTION
**Pull request by vidhan13j07**
Changes proposed in this pull request:
- [x] Remove the images from wikipedia. 
- [x] Add newly created images
- [x] Fix `doc-pgr_lineGraph.queries`

@pgRouting/admins

### CODE REVIEW

**Comment by cvvergara** [comment]
Q. did you use a subgraph of the sample data graph?

**Comment by cvvergara** [comment]
Can you make the visual example using nodes & edge numbers from the sample data graph please

**Comment by vidhan13j07** [comment]
Sure, I'll update the example.

**Comment by vidhan13j07** [comment]
@cvvergara I have updated the images.

**Pull request merged**
