### PR TITLE
PL/pgSQL function to label edges based on the connected graph they belong to

### PR DESCRIPTION
**Pull request by Zia-**
In response to the suggestion suggested by @woodbri https://github.com/pgRouting/osm2pgrouting/issues/8#issuecomment-118360398 , to calculate and locate the total number of disconnected sub-graphs within a graph.

Function has been tested for two graphs. Criticism is heartily welcomed.

### CODE REVIEW

**Comment by Zia-** [comment]
@woodbri I am not sure exactly how to generate those *.data, *.test and *.rest files https://github.com/pgRouting/osm2pgrouting/pull/69 . Existing functions suggest this generation to be an automated processes. or am I wrong? Please guide.

Plus where to update in the following CMakeLists.txt?

    SET(PACKAGE_SQL_FILES "")
    ADD_SUBDIRECTORY(sql)
    SET(PACKAGE_SQL_FILES "${PACKAGE_SQL_FILES}" PARENT_SCOPE)
    #MESSAGE("core/common: ${PACKAGE_SQL_FILES}")
    SUBDIRS(doc src test)

**Comment by woodbri** [comment]
The test infrastructure does not use CMakeLists.txt it uses a perl script located at tools/test-runner.pl.
thr *.data files are just SQL statements to create and load data that you need in your test. The only requirement is that you make sure the table name is unique with respect to other *.data files in the same directory. The *.test.sql is just the SQL you want to run that tests your code, should test various combinations of good and bad results.  See the link below for more details and how to create a *.rest file once you have validated the results. 

https://github.com/pgRouting/pgrouting/wiki/2.0-Development-Guidelines-and-Standards#test-standards

You can run the tests on just the common functions like:

```
tools/test-runner.pl -h
tools/test-runner.pl -alg common
```

**Comment by Zia-** [comment]
Thx @woodbri . I have done necessary changes as suggested by you.

Running the command ```psql -U postgres -h localhost -A -t -q -f mytest.test testdb > mytest.rest``` from the terminal (as suggested here https://github.com/pgRouting/pgrouting/wiki/2.0-Development-Guidelines-and-Standards#test-standards) gave the following output. But the auto-generated `pgrouting_brokengraph.rest` file is empty. But I guess it was expected since the function is not supposed to return anything.

    $ psql -U postgres -h localhost -A -t -q -f pgrouting_brokengraph.test broken_graph2 > pgrouting_brokengraph.rest
    psql:pgrouting_brokengraph.test:2: NOTICE:  Success
 
Additionally, I have failed to compile the package. Got the following error message while following COMPILATION steps at https://github.com/pgRouting/pgrouting. Don't know the reason.

    $ cmake -DWITH_DD=ON -DPG_VERSION=9.1 ..
    -- The C compiler identification is GNU 4.8.4
    -- The CXX compiler identification is GNU 4.8.4
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working CXX compiler: /usr/bin/c++ 
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- PGROUTING_GIT_TAG: pgrouting-2.0.0
    -- PGROUTING_GIT_BUILD: 280
    -- PGROUTING_GIT_HASH: 0acd2ea
    -- PGROUTING_GIT_BRANCH: develop
    -- PGROUTING_VERSION_REVISION_NAME: 0acd2ea develop
    -- PGROUTING_VERSION_REVISION_HASH: 0acd2ea
    -- PG_VERSION: 9.1
    -- UNIX=1
    -- WIN32=
    CMake Warning (dev) at CMakeLists.txt:123 (find_package):
    Syntax Warning in cmake code at

    /home/zia/pgrouting/cmake/FindPostgreSQL.cmake:30:60

       Argument not separated from preceding token by whitespace.
        This warning is for project developers.  Use -Wno-dev to suppress it.

    -- PG_VERSION in FindPostgreSQL.cmake is 9.1
    -- POSTGRESQL_EXECUTABLE is POSTGRESQL_EXECUTABLE-NOTFOUND
    -- POSTGRESQL_PG_CONFIG is POSTGRESQL_PG_CONFIG-NOTFOUND
    -- PostgreSQL not found.
    CMake Error at CMakeLists.txt:125 (message):
       Please check your PostgreSQL installation.


    -- Configuring incomplete, errors occurred!
    See also "/home/zia/pgrouting/build/CMakeFiles/CMakeOutput.log".

**Comment by cvvergara** [comment]
@Zia- 
For your function tests:
Say that I am a spanish speaking person and the policies of the company I work for are to have column names in spanish: 
```
select * from pgr_dijkstra( 'select id, salida as source, destino as target, 
     costo as cost from e03.calles', 2, 3)
```
So, table `calles` in schema `e03` has columns `salida` and `destino`.
So, what happens when:
```
SELECT  pgr_brokenGraph('e03.calles', 'subgrafica') 
```

**Comment by Zia-** [comment]
Hmm. Agreed. Let me work on this.

**Comment by Zia-** [comment]
@cvvergara I hope it's better now. Plz check again.

**Comment by cvvergara** [comment]
@Zia- 
Have a look at this file of tests:
https://github.com/Zia-/pgrouting/blob/develop/src/common/test/createTopology-any-01.test
The idea behind those big files of tests is to cover as many scenarios possible from a user.
So I will keep asking:
What happens if the column already exists?
Is a user able to work only on a part of the data?
other functions like pgr_createTopology, can work on part of the table.
For example: have a look to this documentation
https://github.com/Zia-/pgrouting/blob/develop/src/common/doc/functions/analyze_graph.rst

**Comment by Zia-** [comment]
@cvvergara Sorry for being late. I have done some major changes in my code to incorporate as many possible scenarios from the user. I took immense help from `pgr_analyzeGraph` documentation and tried to adhere the norms. Thanks for the link.
I have already done testing on two networks. And now will eagerly look forward for your comments.
Apologies if I missed something major.

**Comment by cvvergara** [comment]
@Zia- 
I went to see your repository, we are still in the alpha phase, so we are kind of "on time" .
I certainly want to add your function, and here is my proposal:
We can add your function in the "recipes" (since its new, we can place it there and have people test it)
but (as always there is a but)
I went to see [your repository](https://github.com/Zia-/pgrouting) and it says:
```
This branch is 11 commits ahead, 201 commits behind pgRouting:develop
```
Before even trying to make a pull request you need to synchronize develop in your fork develop in the  the main repository.
here are some useful steps
1. make a backup (allways healthy to do)
```
#in develop
git checkout -b develop-broken-graph 
git checkout develop
```
2. synchronize your fork. this [instructions] (https://help.github.com/articles/syncing-a-fork/) I find them useful
3. After that synchronisation, run the tests
4. All alpha changes I will be doing in develop_2_1_0 branch so create the pull request to that branch

**Comment by cvvergara** [comment]
@Zia- 
I am closing this pull request, but if you have questions of the process I mentioned, you can still ask here.

**Comment by cvvergara** [comment]
@Zia- 
Just being curious, how is it going?

**Comment by Zia-** [comment]
@cvvergara Thanks a lot Vicky for your concern. Unfortunately was hell busy this week replying paper reviews and preparing PhD reports. So couldn't get good time.  
I'll for sure let you know my progress ASAP. I'll also try to learn some tech know-hows of git, as I can see that I am making some fundamental mistakes. 
But meanwhile, I am keeping a track over your conversations on pgrouting/osm2pgrouting and must say that you have a managerial personality :-)

**Comment by Zia-** [comment]
@cvvergara So I did the following steps. 

    git checkout -b develop-broken-graph-backup-0.1
    git checkout develop
    git remote add upstream https://github.com/pgRouting/pgrouting.git
    git fetch upstream
    git checkout develop 
    git merge upstream/develop

#During the above step the merge upstream branch should be develop or develop_2_1_0? Although I have done with develop but was suspicious.

    git add README.md
    git add VERSION
    git add src/common/sql/CMakeLists.txt

#I have added the above three files as there was some merge confliction and I found that to be the solution (https://help.github.com/articles/resolving-a-merge-conflict-from-the-command-line/)

    git commit -m 'added README.md VERSION src/common/sql/CMakeLists.txt'
    git push

What kind of testing you are talking about? Do you mean travis?
> After that synchronisation, run the tests

Am I good to go to create a pull request of my develop branch (https://github.com/Zia-/pgrouting) now against `develop_2_1_0` branch?

**Comment by cvvergara** [comment]
@Zia- 
yes to develop_2_1_0 and that will automatically run the travis tests.
We make the examples in the documentation against the [sample data](http://docs.pgrouting.org/v2.1.0-alpha/doc/src/developer/sampledata.html#sampledata), but because it is going to be placed in the proposed functions, we can keep it like that. And we can work out the details latter on.

**Comment by cvvergara** [comment]
The merge was closed because its not passing the tests.
https://travis-ci.org/pgRouting/pgrouting/builds/72427546
https://travis-ci.org/pgRouting/pgrouting/jobs/72427547#L1828

**Pull request closed without merging**
