### PR TITLE
[WIP]Doc/pgr_areaContraction

### PR DESCRIPTION
**Pull request by daas-ankur-shukla**
Fixes [#32](https://github.com/daas-ankur-shukla/pgrouting/issues/32) .

Changes proposed in this pull request:
- Added onetomany path images (However I am getting an error for those files)
- Added to the proposal documentation

@pgRouting/admins

### CODE REVIEW

**Comment by cvvergara** [comment]
I got this errors:
Did you get them in locally when you generated the documentation locally?
```
/home/vicky/pgrouting/pgrouting/pgrouting/build/doc/areaContraction.rst:83: WARNING: image file not readable: images/onetomany_a.png
/home/vicky/pgrouting/pgrouting/pgrouting/build/doc/areaContraction.rst:89: WARNING: image file not readable: images/onetomany_b.png
/home/vicky/pgrouting/pgrouting/pgrouting/build/doc/areaContraction.rst:95: WARNING: image file not readable: images/onetomany_c.png
/home/vicky/pgrouting/pgrouting/pgrouting/build/doc/areaContraction.rst:100: WARNING: image file not readable: images/onetomany_d.png
pgRouting-concepts.rst:3: SEVERE: Title level inconsistent:

Description of the return values for a path
...............................................................................
```

**Comment by cvvergara** [comment]
you didnt configure all the images files (might be the reason for the "image not readable")
https://github.com/daas-ankur-shukla/pgrouting/blob/doc/areaC13/doc/areaContraction/images/CMakeLists.txt

**Comment by cvvergara** [comment]
Your .png files have permission to execute, are you injecting a virus?
```
-rwxrwxr-x 
```

Fix that with
```
chmod -x *.png
```
the permissions should be:
```
-rw-rw-r--
```

**Comment by cvvergara** [comment]
Remove the 
```
documentation.sh
run_new.sh
```
From the `.gitignore` file

`.gitignore` is a file that affects all of us ...
For years I see my
```
decumentation.sh
run.sh
```
when I do a git status, just to make sure that I didn't add it to a commit.


```
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        gsoc2017/
        publish.sh
        result.txt
        run.sh
        src/trsp/doc/
        steps.txt
        translate.sh
        try1.txt
        try2.txt
        try3.txt
```
Those files I want them untracked, but I want to be able to see what I haven't added to a commit.
so, if its not in the list:
* because I deleted the file
* or because its in the commit

now my documentation.sh does not show any more, doing an `ls` its there, and I didn't add it to a commit.  you are making me ignore something that I don't want to ignore.

**Comment by cvvergara** [comment]
I'll fix this error:
```
pgRouting-concepts.rst:3: SEVERE: Title level inconsistent:

Description of the return values for a path
...............................................................................
```

**Comment by daas-ankur-shukla** [comment]
@cvvergara maam i have read the comments just now. doing the needful

**Pull request merged**
