### PR TITLE
[GSoC-2023] Modifying - withpointsdd

### PR DESCRIPTION
**Pull request by squarege**
This PR modifies one existing function:

- ``pgr_withPointsDD``: 
  - Improving the 'driver_side' optional parameter to compulsory parameter.
  - Adding one new result column 'depth'.
  - Normalizing the output.

This is a final merge PR containing commits from several different PRs combined.

The intermediate PRs made on the [GSoC-pgRouting](https://github.com/pgRouting/GSoC-pgRouting/) repository are as follows:

| Description |  Pull Requests |
| -----------| --------------------- |
| pgr_withPointsDD | <ul><li>pgRouting/GSoC-pgRouting#291</li><li>pgRouting/GSoC-pgRouting#299</li><li>pgRouting/GSoC-pgRouting#303</li><li>pgRouting/GSoC-pgRouting#309</li><li>pgRouting/GSoC-pgRouting#313</li><li>pgRouting/GSoC-pgRouting#318</li><li>pgRouting/GSoC-pgRouting#324</li><li>pgRouting/GSoC-pgRouting#325</li><li>pgRouting/GSoC-pgRouting#332</li><li>pgRouting/GSoC-pgRouting#335</li><li>pgRouting/GSoC-pgRouting#341</li><li>pgRouting/GSoC-pgRouting#350</li></ul> |

The wiki page with more details on this project can be found [here](https://github.com/pgRouting/pgrouting/wiki/GSoC-2023-Improving-Parameters-and-Standardizing-Results-in-pgr_withPointsDD-Function-for-pgRouting).

### CODE REVIEW

**Review by cvvergara — APPROVED** [review]

**Comment by cvvergara** [comment]
Codacy errors are ignored

**Review by cvvergara — APPROVED** [review]

**Review by krashish8 — APPROVED** [review]
Looks good!
Thanks for all the efforts 🎉  @squarege

**Review by robe2 — APPROVED** [review]
Looks good.

**Review by shobhit162 — APPROVED** [review]
Looks good.
Thanks @squarege for your contributions!

**Pull request merged**
