### PR TITLE
fix 2394 : don't store heuristic cost into cost vector

### PR DESCRIPTION
**Pull request by AlexGacon**
Fixes #3294 .

Changes proposed in this pull request:
- No longer store heuristic code into node cost vector and use it only to best candidate selection
-
-

@pgRouting/admins

### CODE REVIEW

**Comment by cvvergara** [comment]
@AlexGacon 
We don't have an issue number 3294

But we do need an issue.
Please open an issue giving at lease one example with each heuristic, stating what is the current result, what is the expected result and why.

Optionally:
Based on the issue, we need a pgtap test that passes on the version intended to be fixed, and fails on versions less that than version intended to be merged. Preferably using the sample data network.
and a note on the release_notes.rst about the change, 
Then execute: 
tools/release-scripts/notes2news.pl
Update the results of the queries of the documentation by running:
tools/testers/doc_queries_generator.pl -doc

Please let me know if you plan to do the optional part, otherwise someone on the team needs to do it before it is merged.

**Comment by cvvergara** [comment]
If you need help on doing the optional part, you can reach us the pgRouting gitter chat.

**Comment by AlexGacon** [comment]
@cvvergara sorry, I put the figures in the wrong order. This PR is meant to fix #2394.

**Comment by cvvergara** [comment]
Oh, yes that happnes.

we still need a pgtap test and everything I mentioned before.
Can you do it?

Currently I am working on fixing a critical bug for 3.4.1 (main) before releasing it. and I have to release it today.
otherwise it would go to 3.4.2

**Comment by cvvergara** [comment]
PR included in #2437

**Pull request closed without merging**
