### PR TITLE
Dijkstra doc

### PR DESCRIPTION
**Pull request by MarPetra**
Fixes #1100  for:
-  pgr_dijkstra
- pgr_dijkstraCost

@pgRouting/admins

### CODE REVIEW

**Comment by MarPetra** [comment]
* I couldn't fix 4 warnings

**Comment by cvvergara** [comment]
I will generate the documentation, please stay put

**Comment by cvvergara** [comment]
https://docs.pgrouting.org/dev/en/pgr_dijkstra.html
https://docs.pgrouting.org/dev/en/pgr_dijkstraCost.html

**Comment by cvvergara** [comment]
Perfect, please continue :) with the functions of your preference

**Pull request merged**
