### PR TITLE
Translations update from OSGeo Weblate

### PR DESCRIPTION
**Pull request by osgeoweblate**
Translations update from [OSGeo Weblate](https://weblate.osgeo.org) for [pgRouting/pgRouting](https://weblate.osgeo.org/projects/pgrouting/pgrouting-develop/).

It also includes following components:

* [pgRouting/index](https://weblate.osgeo.org/projects/pgrouting/index/)

Current translation status:

Weblate translation status

**Reminder**: Do not squash, do a rebase

### CODE REVIEW

**Comment by cvvergara** [comment]
@w345731923

Are you translating to Chinese?
I am testing and getting lots of errors on the Chinese translation
https://github.com/cvvergara/pgrouting/actions/runs/6579979298/job/17876988461

**Comment by w345731923** [comment]
@cvvergara 

Yes, I'm doing it.
I'll handle these errors.

**Comment by w345731923** [comment]
@cvvergara 
I noticed two types of problems: one was the lack of closing punctuation, and the other was the lack of translation. 
When we reach 100% completion, I will notify you to pack again.

**Comment by w345731923** [comment]
@cvvergara 

The Chinese translation has been fully completed, please try to build.
https://weblate.osgeo.org/projects/pgrouting/pgrouting-develop/zh_Hans/

**Comment by cvvergara** [comment]
Hi @w345731923  We will mere all the work done, as we need to move things to main branch.
Translation to chinese  will not be published until we finish fixing the sphinx translation issues.

**Pull request merged**
