### PR TITLE
Changes before release

### PR DESCRIPTION
**Pull request by cvvergara**
Changes proposed in this pull request:
- version 3.2.0-dev -> 3.2.0
- fix macos action
- fix macos warnings
- getting latest translations from spanish

@pgRouting/admins

### CODE REVIEW

**Review by robe2 — APPROVED** [review]

**Review by krashish8 — APPROVED** [review]

**Review by dkastl — APPROVED** [review]

**Review by cayetanobv — APPROVED** [review]
I'm going to prepare the new version at pgRouting for Docker repo.

**Review by omshinde — APPROVED** [review]
Thanks!

**Comment by cvvergara** [comment]
@cayetanobv 
The most important change for building is about the boost version
https://docs.pgrouting.org/dev/en/release_notes.html#pgrouting-3-2-0-release-notes
I think it will not affect you, but be aware

**Comment by cvvergara** [comment]
@cayetanobv 
https://github.com/pgRouting/pgrouting/tree/develop#building-requirements

**Comment by cayetanobv** [comment]
> @cayetanobv
> The most important change for building is about the boost version
> https://docs.pgrouting.org/dev/en/release_notes.html#pgrouting-3-2-0-release-notes
> I think it will not affect you, but be aware

Thanks @cvvergara . I'm going to review this change in the building process.

**Comment by cayetanobv** [comment]
> > @cayetanobv
> > The most important change for building is about the boost version
> > https://docs.pgrouting.org/dev/en/release_notes.html#pgrouting-3-2-0-release-notes
> > I think it will not affect you, but be aware
> 
> Thanks @cvvergara . I'm going to review this change in the building process.

I reviewed the change and we are compiling with boost 1.67.

**Pull request merged**
