### PR TITLE
Do not override host, port and user in connection parameters for tests

### PR DESCRIPTION
**Pull request by grayed**
Do not override host, port and user in connection parameters,
unless explicitly specified. This allows usual Postgres rules apply,
e.g., PGHOST, PGPORT and PGUSER environment variables. In particular,
non-network connections could be used now, which is preferred for
automated testing.

Travis test runner script is adapted to changes, too.

### CODE REVIEW

**Comment by grayed** [comment]
The feature being discussed is used, in particular, in OpenBSD Ports, see an example:
http://cvsweb.openbsd.org/cgi-bin/cvsweb/ports/databases/postgresql/postgresql.port.mk?rev=1.2&content-type=text/x-cvsweb-markup

**Comment by cvvergara** [comment]
Ok, looks like you've nailed it.
I'll merge after it finishes.
We all appreciate your effort.

**Comment by cvvergara** [comment]
If I have a Q while I fix it for windows I will post a note here.

**Comment by cvvergara** [comment]
@grayed 
I think I need your help here:
https://github.com/pgRouting/pgrouting/blob/develop-2_0_1/tools/winnie/build_pgrouting.sh#L81
I am getting this error on some the winnie tests
http://winnie.postgis.net:1500/view/pgRouting/job/pgRouting_2_PGVersion/1976/console
(scroll almost to the bottom)

**Comment by cvvergara** [comment]
@robe2 Regina
actually is only on that test.
RUNNING: test-runner.pl -pgver 9.4 -pgisver 2.1.7 -pgport 10446 -ignorenotice -clean
dropdb: could not connect to database template1: could not connect to server: Connection refused (0x0000274D/10061)
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 10446?
could not connect to server: Connection refused (0x0000274D/10061)
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 10446?

**Pull request merged**
