### PR TITLE
Closes #1359 Adding pgr_dijkstra(combinations)

### LINKED ISSUE #1359: pgr_dijkstra combinations SQL
My program needs to compute the shortest path between millions of (source, target) combinations on the same edges_table. It is very inefficient to do millions of calls to pgr_dijkstra, each of which will construct the same graph from the edges_table.   
 
An efficient way to do it is to add a new signature as follows:
pgr_dijkstra(
   edges_sql,
   combinations_sql, -- a table (possibly big) of with two attributes source, target
   directed)
Like this, one call will constrcut the graph once, and compute as many shortest paths as returned by the combinations_sql.

### PR DESCRIPTION
**Pull request by mahmsakr**
Fixes # .

Changes proposed in this pull request:
- gpr_dijkstra combination_sql signature
- documentation of the new function
- developer names

@pgRouting/admins

### CODE REVIEW

**Comment by cvvergara** [comment]
@mahmsakr Thanks for your contribution to pgRouting

**Comment by dkastl** [comment]
What is the difference between the new `combinations` SQL and the `many-to-many`?

Isn't `many-to-many` or other signatures possible to be used as `combinations`?

**Comment by mahmsakr** [comment]
Many-to-many does a cross product. So if the array of sources has [3, 5]
and the array of targets has [7, 11], dijkstra is calculated for:
3 -> 7
3-> 11
5 -> 7
5 -> 11

The combinations SQL gives full control on which combinations are desired.
For example, given the following query:

SELECT * FROM pgr_dijkstra(
    'SELECT id, source, target, cost, reverse_cost FROM edge_table',
    'SELECT * FROM (VALUES (3, 11), (5, 7)) AS combinations (source, target)');

dijkstra will only be calculated for
3 -> 11
5 -> 7


Best regards,
Mahmoud

**Comment by dkastl** [comment]
@mahmsakr , thanks! Then I understand it right.

I was wondering if the new signature doesn't allow us to remove other signatures then, because they could be just special cases of the `combinations` SQL.

For example a distance matrix matrix of two source and target pairs could be written as 4 combinations. Even a standard `A -> B` route would be a case that consists of just one combination.

So instead of maintaining several signatures we could use the new signature as default, and there could be some helper functions for example to turn a many-to-many matrix into combinations.

**Comment by mahmsakr** [comment]
Hi Daniel,
Your idea is technically correct. The combinations SQL signature has an
equivalence to each of the three existing signatures. So it can express all
of them, and give the same result.
From a usability aspect, the other signature can be more flexible in
certain cases. This is a factor that needs also to be taken into
consideration.

Best regards,
Mahmoud

**Pull request merged**
