### PR TITLE
postgre 14->15

### PR DESCRIPTION
**Pull request by aryan1010**
Fixes # .

Changes proposed in this pull request:
-Installation  part of document has been modified
-PostgresQL  14 is changed to  PostgresQL  15
-

@pgRouting/admins

### CODE REVIEW

**Review by robe2 — APPROVED** [review]
Looks fine.  Should also go into develop

**Comment by cvvergara** [comment]
@aryan1010 
As mentioned by @robe2 please make the PR to develop branch.
We are close to move develop branch to main branch.
(You might need to start over or do a cherry pick)
And now that you are on it:
https://github.com/pgRouting/pgrouting/blob/develop/.github/workflows/ubuntu.yml#L32
Please add to the workflow for postgres 15
and if it works then also commit that change.

**Comment by aryan1010** [comment]
@cvvergara  yes mam ,i have made another pull request.
ok mam i will commit

**Comment by aryan1010** [comment]
@cvvergara  mam,the task you have given ,you mean , i have to put another pull request right,because how can i commit directly without being  a contributor.

**Pull request closed without merging**
