### PR TITLE
fix for archlinux pgrouting 1.05 compilation

### PR DESCRIPTION
**Pull request by albfan**
I now 1.x it is not maintaned, but this helps to compile.

https://github.com/albfan/pgrouting-pkgbuild.git can be used meanwhile AUR package is created

### CODE REVIEW

**Comment by albfan** [comment]
it is based on pgrouting-1.05 tag (For those curious about github warning on conflicts) It is not supposed to be merged on master

**Comment by dkastl** [comment]
Thank you for caring about this!
As the support for this version of pgRouting has ended and your pull request seems to require conflict resolution, I leave this pull request for users, who need it but won't merge it.

**Comment by albfan** [comment]
Yes, Is funny github only tries to merge master with PR (obviously with conflicts). Comparing changes with tag 1.05 shows a clean merge.

Here is AUR package for arch linux based on fork.

https://aur.archlinux.org/packages/pgrouting-1.x/

**Comment by dkastl** [comment]
OK. Thanks for the link and creating packages!
Nevertheless I would highly recommend to drop support for pgRouting 1.05 as it has been unsupported for many years now.

**Comment by dkastl** [comment]
@albfan are there any reasons not to build packages for pgRouting 2.1 for Archlinux?

**Comment by dkastl** [comment]
I also realized that the "Upstream URL" to the pgRouting project is not valid anymore: 
`Upstream URL:	http://pgrouting.postlbs.org`

That's something that has changed already 2008 or even earlier.

**Pull request closed without merging**
