### PR TITLE
feat. Add Chinese translation.

### PR DESCRIPTION
**Pull request by w345731923**
Hello everyone,

The template file was added and I translated it into Chinese.

Thanks,
Wangdapeng

@pgRouting/admins

### CODE REVIEW

**Comment by cvvergara** [comment]
@w345731923 
I need to test locally as the we are not currently testing Chinese on the CI.


We are using [Weblate software](https://weblate.org/) for translation. If you want to help out, log into [OSGeo Weblate](https://weblate.osgeo.org/projects/pgrouting/).

If you don't already have an OSGeo account, [you can get one here](https://id.osgeo.org/ldap/create). An OSGeo account will allow you to participate in translating many other OSGeo projects also.

**Comment by cvvergara** [comment]
Sorry, This can not be merged,
There is no translation happening, the file has only the original strings:
https://github.com/pgRouting/pgrouting/blob/ad20fa528187c43361d8dc32504b67bc8c7d8902/locale/zh/LC_MESSAGES/pgrouting_doc_strings.po

We are using [Weblate software](https://weblate.org/) for translation. If you want to help out, log into [OSGeo Weblate](https://weblate.osgeo.org/projects/pgrouting/).

If you don't already have an OSGeo account, [you can get one here](https://id.osgeo.org/ldap/create). An OSGeo account will allow you to participate in translating many other OSGeo projects also.

**Comment by w345731923** [comment]
I have an OSGeo Weblate account, please create a new Chinese folder.

**Comment by w345731923** [comment]
@cvvergara 
I am submitting this submission also to create a folder and prepare to translate it on weblate.

**Comment by w345731923** [comment]
@cvvergara Sorry, I see that Chinese translation is being used. Zuochenwei has worked on translation. Could you please add Zuochenwei's name or HighGo ([www.highgo.ca](http://www.highgo.ca/)) company?

**Comment by w345731923** [comment]
> @cvvergara Sorry, I see that Chinese translation is being used. Zuochenwei has worked on translation. Could you please add Zuochenwei's name or HighGo ([www.highgo.ca](http://www.highgo.ca/)) company?

My name is Wang Dapeng, and I will continue to provide Chinese translations for the community.

**Pull request closed without merging**
