### PR TITLE
[WIP] Documentation and Implementation of pgr_prim

### PR DESCRIPTION
**Pull request by apslight**
### Use boost visiter to  trace the path of prim  

- [x] fix 'pgr_prim.hpp'

### Test Directory 
- [x] Create 'test.conf'
- [x] Create 'doc-prim.result'
- [x] Create 'doc-prim.test.sql' 

### Doc Directory 
- [x] Create 'CMakeLists.txt'
- [x] Create 'doc-pgr_prim.queries'
- [x] Create 'pgr_prim.rst' 

### pgTap Directory
- [ ] Create '.sql ' files

### CODE REVIEW

**Comment by apslight** [comment]
Previous result of pgr_prim for rsample data
```
 seq | start_node | end_node | edge | cost | agg_cost 
-----+------------+----------+------+------+----------
   1 |          1 |       -1 |   -1 |    0 |        0
   2 |          2 |        1 |    1 |    1 |        1
   3 |          3 |        2 |    2 |    1 |        2
   4 |          4 |        3 |    3 |    1 |        3
   5 |          5 |        2 |    4 |    1 |        4
   6 |          6 |        3 |    5 |    1 |        5
   7 |          7 |        8 |    6 |    1 |        6
   8 |          8 |        5 |    7 |    1 |        7
   9 |          9 |        6 |    9 |    1 |        8
  10 |         10 |        5 |   10 |    1 |        9
  11 |         11 |        6 |   11 |    1 |       10
  12 |         12 |       11 |   13 |    1 |       11
  13 |         13 |       10 |   14 |    1 |       12
  14 |         14 |       -1 |   -1 |    0 |       12
  15 |         15 |       -1 |   -1 |    0 |       12
  16 |         16 |       -1 |   -1 |    0 |       12
  17 |         17 |       -1 |   -1 |    0 |       12
(17 rows)
```
Improve result:
```
 seq | start_node | end_node | edge | cost | agg_cost 
-----+------------+----------+------+------+----------
   1 |          1 |       -1 |   -1 |    0 |        0
   2 |          2 |        1 |    1 |    1 |        1
   3 |          3 |        2 |    2 |    1 |        2
   4 |          4 |        3 |    3 |    1 |        3
   5 |          5 |        2 |    4 |    1 |        4
   6 |          6 |        3 |    5 |    1 |        5
   7 |          7 |        8 |    6 |    1 |        6
   8 |          8 |        5 |    7 |    1 |        7
   9 |          9 |        6 |    9 |    1 |        8
  10 |         10 |        5 |   10 |    1 |        9
  11 |         11 |        6 |   11 |    1 |       10
  12 |         12 |       11 |   13 |    1 |       11
  13 |         13 |       10 |   14 |    1 |       12
   1 |         14 |       -1 |   -1 |    0 |        0
   2 |         15 |       14 |   17 |    1 |        1
   1 |         16 |       -1 |   -1 |    0 |        0
   2 |         17 |       16 |   18 |    1 |        1
(17 rows)
```

**Comment by apslight** [comment]
New result:
```
 seq | prim_path | start_node | end_node | edge | cost | agg_cost 
-----+-----------+------------+----------+------+------+----------
   1 |         1 |          1 |       -1 |   -1 |    0 |        0
   2 |         2 |          2 |        1 |    1 |    1 |        1
   3 |         3 |          3 |        2 |    2 |    1 |        2
   4 |         4 |          4 |        3 |    3 |    1 |        3
   5 |         5 |          5 |        2 |    4 |    1 |        4
   6 |         6 |          6 |        3 |    5 |    1 |        5
   7 |         7 |          7 |        8 |    6 |    1 |        6
   8 |         8 |          8 |        5 |    7 |    1 |        7
   9 |         9 |          9 |        6 |    9 |    1 |        8
  10 |        10 |         10 |        5 |   10 |    1 |        9
  11 |        11 |         11 |        6 |   11 |    1 |       10
  12 |        12 |         12 |       11 |   13 |    1 |       11
  13 |        13 |         13 |       10 |   14 |    1 |       12
  14 |         1 |         14 |       -1 |   -1 |    0 |        0
  15 |         2 |         15 |       14 |   17 |    1 |        1
  16 |         1 |         16 |       -1 |   -1 |    0 |        0
  17 |         2 |         17 |       16 |   18 |    1 |        1
(17 rows)
```

**Comment by cvvergara** [comment]
I am very ignorant, about what Prim algorithm does
I am trusting you :)
just tell me when the documentation is finished so it has an explanation and then we check if the result is ok or not

**Comment by apslight** [comment]
@cvvergara Ma'am I have done Documentaion please have a look
https://apslight.github.io/doc/html/en/pgr_prim.html
though html file is not good but you can read main content.

**Comment by apslight** [comment]
New results:
Query :1
```
SELECT * FROM pgr_prim(
    'SELECT id, source, target, cost, reverse_cost FROM edge_table', -1
);
 seq | prim_tree | start_node | end_node | edge | cost | agg_cost 
-----+-----------+------------+----------+------+------+----------
   1 |         1 |          1 |       -1 |   -1 |    0 |        0
   2 |         1 |          1 |        2 |    1 |    1 |        1
   3 |         1 |          2 |        3 |    2 |    1 |        2
   4 |         1 |          2 |        5 |    4 |    1 |        3
   5 |         1 |          3 |        6 |    5 |    1 |        4
   6 |         1 |          5 |       10 |   10 |    1 |        5
   7 |         1 |          6 |       11 |   11 |    1 |        6
   8 |         1 |         10 |       13 |   14 |    1 |        7
   9 |         1 |         11 |       12 |   13 |    1 |        8
  10 |         1 |          6 |        9 |    9 |    1 |        9
  11 |         1 |          5 |        8 |    7 |    1 |       10
  12 |         1 |          3 |        4 |    3 |    1 |       11
  13 |         1 |          8 |        7 |    6 |    1 |       12
  14 |         2 |         14 |       -1 |   -1 |    0 |        0
  15 |         2 |         14 |       15 |   17 |    1 |        1
  16 |         3 |         16 |       -1 |   -1 |    0 |        0
  17 |         3 |         16 |       17 |   18 |    1 |        1
(17 rows)
```
Query :2
```
SELECT * FROM pgr_prim(
    'SELECT id, source, target, cost, reverse_cost FROM edge_table', 4
);
 seq | prim_tree | start_node | end_node | edge | cost | agg_cost 
-----+-----------+------------+----------+------+------+----------
   1 |         1 |          4 |       -1 |   -1 |    0 |        0
   2 |         1 |          4 |        3 |    3 |    1 |        1
   3 |         1 |          4 |        9 |   16 |    1 |        2
   4 |         1 |          3 |        6 |    5 |    1 |        3
   5 |         1 |          9 |       12 |   15 |    1 |        4
   6 |         1 |          6 |       11 |   11 |    1 |        5
   7 |         1 |          6 |        5 |    8 |    1 |        6
   8 |         1 |         11 |       10 |   12 |    1 |        7
   9 |         1 |          5 |        8 |    7 |    1 |        8
  10 |         1 |         10 |       13 |   14 |    1 |        9
  11 |         1 |          8 |        7 |    6 |    1 |       10
  12 |         1 |          3 |        2 |    2 |    1 |       11
  13 |         1 |          2 |        1 |    1 |    1 |       12
(13 rows)
```
Query :3
```
SELECT * FROM pgr_prim(
    'SELECT id, source, target, cost, reverse_cost FROM edge_table where id > 10', 9
);
 seq | prim_tree | start_node | end_node | edge | cost | agg_cost 
-----+-----------+------------+----------+------+------+----------
   1 |         1 |          9 |       -1 |   -1 |    0 |        0
   2 |         1 |          9 |       12 |   15 |    1 |        1
   3 |         1 |          9 |        4 |   16 |    1 |        2
   4 |         1 |         12 |       11 |   13 |    1 |        3
   5 |         1 |         11 |        6 |   11 |    1 |        4
   6 |         1 |         11 |       10 |   12 |    1 |        5
   7 |         1 |         10 |       13 |   14 |    1 |        6
(7 rows)
```

**Pull request merged**
