### PR TITLE
changes in documentation

### PR DESCRIPTION
**Pull request by sarthak-0415**
Some Changes in the documentation : 
1. less ambigous statements.
2. fixed bug #270 for some of the files (other files i was not able to find in the code ).
3. converted some inline command statements into italics for differentiation between commands and words .

### CODE REVIEW

**Comment by dkastl** [comment]
Thanks a lot!
I think you picked a very suitable issue for this purpose.

There is just one thing, which I haven't explained and it would be better to write it down somewhere:
Can you try to submit the pull request against the `develop` branch. It's also good to work based on the `develop` branch, because it is usually newer than `master`.

So, not your fault with the wrong branch. It happens almost with every pull request, so we may have to find a suitable place to provide this information.

**Comment by woodbri** [comment]
You might want to read up an the git command rebase, this basically let you migrate a pull request to another branch like develop.

**Comment by sarthak-0415** [comment]
Thank you for the reply Daniel and Stephen.
I have merged my branch in to the develop branch.

Sarthak

**Comment by dkastl** [comment]
@sarthak-0415 can this pull request closed in favor of #300 ?

**Comment by sarthak-0415** [comment]
Yes , I changed the documentation a bit, there were other changes required
in #300 but i couldn't find the files.

Sarthak

**Comment by cvvergara** [comment]
pull request to the wrong branch. closing

**Pull request closed without merging**
