### PR TITLE
fixed pgr_pointsAsPolygon breaking when comparing strings in WHERE clause

### LINKED ISSUE #1192: pgr_pointsAsPolygon doesn't play nice if you have string comparisons in the WHERE clause
I recently had some difficulty in using a ``WHERE` clause that included a string comparison in this function. The problem stems from the fact that this function immediately calls another function which uses the typical pgRouting "query as a string parameter" methodology.

### Expected behavior and actual behavior

Consider this query:

```
SELECT
	pgr_pointsAsPolygon(
	'SELECT
		id,
		ST_X(geom)::float AS x,
		ST_Y(geom)::float AS y
	FROM
		myschema.mytable
	WHERE
		mode = ''walk'';'
	)
```

This crashes with a syntax error generated from the subsequent call to `pgr_alphaShape(...)`, because it is just forwarding the pgr string, which results in this:
```

SELECT x, y FROM pgr_alphashape('SELECT
	id,
	ST_X(geom)::float AS x,
	ST_Y(geom)::float AS y
FROM
  	myschema.mytable
WHERE
	mode = 'walk';',
0)
```

Because the single quotes around `walk` are not escaped, it results in a mangled query and therefore a syntax error.
After fiddling around with this for a while with a colleague, we were finally able to get the desired behaviour with this query:

```
WITH tbl AS (SELECT '''walk''' AS walk)

SELECT
	pgr_pointsAsPolygon(
		FORMAT(
			'SELECT
				id,
				ST_X(geom)::float AS x,
				ST_Y(geom)::float AS y
			FROM
				myschema.mytable
			WHERE
				mode = ''%s'';
			',
			(SELECT walk FROM tbl)
		)
	) AS pap
```

It's not pretty, but it works. Basically we wrap the pgr query string in a `FORMAT()` call and load a string from a common table expression (which itself has to contain escaped single quotes).

### Steps to reproduce the problem

Sorry that I don't have a sample dataset, but the idea is rather simple. Just try to call `pgr_pointsAsPolygon` with a query string which makes a string comparison in the `WHERE` clause.

### Specifications like the version of pgRouting/PostGIS and PostgreSQL as well as Operating System

- OS: Windows 10
- PostgreSQL: 10.7
- PostGIS: 2.5
- pgRouting: 2.6.2

### PR DESCRIPTION
**Pull request by iboates**
Fixes #1192 .

Changes proposed in this pull request:
- Replace single quotes in the query passed to `pgr_pointsAsPolygon()` with escaped quotes, stopping a failure if a string comparison is specified in its `WHERE` clause in the subsequent call to `pgr_alphaShape()`

@pgRouting/admins

### CODE REVIEW

**Comment by iboates** [comment]
You can use this query to test with & without this update.

Before, it should throw a syntax error from pgr_alphaShape. After, it should execute as normal.

```
CREATE TABLE public.alphashape_fix_points (
    id bigint,
    text_col text
);
INSERT INTO public.alphashape_fix_points (id, text_col) VALUES (102, 'foo');
INSERT INTO public.alphashape_fix_points (id, text_col) VALUES (154, 'foo');
INSERT INTO public.alphashape_fix_points (id, text_col) VALUES (155, 'foo');
INSERT INTO public.alphashape_fix_points (id, text_col) VALUES (156, 'foo');
INSERT INTO public.alphashape_fix_points (id, text_col) VALUES (157, 'foo');
INSERT INTO public.alphashape_fix_points (id, text_col) VALUES (161, 'foo');
INSERT INTO public.alphashape_fix_points (id, text_col) VALUES (190, 'bar');
INSERT INTO public.alphashape_fix_points (id, text_col) VALUES (191, 'bar');
INSERT INTO public.alphashape_fix_points (id, text_col) VALUES (237, 'bar');
INSERT INTO public.alphashape_fix_points (id, text_col) VALUES (251, 'bar');
INSERT INTO public.alphashape_fix_points (id, text_col) VALUES (276, 'bar');
INSERT INTO public.alphashape_fix_points (id, text_col) VALUES (285, 'bar');

SELECT
    pgr_pointsAsPolygon(
        'SELECT
            id::INT4,
            ST_X(the_geom)::float AS x,
            ST_Y(the_geom)::float AS y
        FROM
            work.cur_net_vertices_pgr
        WHERE
            text_col =  ''foo'';'
);
```

**Comment by cvvergara** [comment]
Hello @iboates 
I really don't understand the error being fixed, but I trust you :)

There is a typo on a test file (I really dont know how it came to pgRouting
https://github.com/pgRouting/pgrouting/blob/master/pgtap/common/hasnt_v2_signatures.sql#L33
Can you change from this:
```
SELECT hasnt_function('pgr_tsp',ARRAY['(double precision[]', 'integer', 'integer']);
```
to this
```
SELECT hasnt_function('pgr_tsp',ARRAY['double precision[]', 'integer', 'integer']);
```
in your PR, so that tests pass and then I am able to merge please

FYI,
This function will be deprecated on v3.0.0
because of #1188 

I would really appreciate if you try the new function on some real data
https://docs.pgrouting.org/dev/en/pgr_alphaShape.html

**Comment by iboates** [comment]
@cvvergara Is there still a separate function for `pgr_alphaShape` and `pgr_pointsFromPolygon`? All I see is a single function for `pgr_alphaShape` here: https://github.com/pgRouting/pgrouting/blob/develop/sql/alpha_shape/alphaShape.sql

**Comment by cvvergara** [comment]
@iboates 
we are only keeping one function
when those functions were introduced:
pgr_pointsAsPolygons calls the pgr_alphaShape that does the calculation, like the backend, but with the name pgr_pointsAsPolygons it could easily call ST_ConcaveHull which gives a polygon as result or ST_ConvexHull which also give a polygon as result.

_pgr_alphaShape (its the backend & does the calculation) & pgr_alphaShape(pre calculates the delauny triangles and calls the backend function) <--- so things look like this now

**Comment by iboates** [comment]
@cvvergara I tested on the 3.0.0 development docker image and it is no longer an issue. The fact that the geometry is passed directly and not via a SQL string means that there is no problem with characters becoming unescaped.

**Comment by iboates** [comment]
@cvvergara Tests now pass

**Pull request merged**
