### PR TITLE
Linting the code for TRSP based on the C and C++ google guidelines.

### PR DESCRIPTION
**Pull request by vidhan13j07**
- [x] src/trsp/src/trsp.c

- [x] src/trsp/src/GraphDefinition.cpp

- [x] src/trsp/src/trsp_core.cpp

- [x] src/trsp/src/trsp_driver.cpp

- [x] src/trsp/src/trsp.h

- [x] src/trsp/src/utils.h

### CODE REVIEW

**Comment by cvvergara** [comment]
My Reviewing:
OK for:
- [ ]  src/trsp/src/trsp.c
- [ ]  src/trsp/src/GraphDefinition.cpp
- [ ]  src/trsp/src/trsp_core.cpp
- [ ]  src/trsp/src/trsp.h
- [ ]  src/trsp/src/utils.h

**Comment by cvvergara** [comment]
@vidhan13j07 
Please provide a description (edit the first comment), it can be the list of tasks, just as you have it in your issue
https://github.com/vidhan13j07/pgrouting/issues/6

**Comment by cvvergara** [comment]
@XJTUmg Add a comment, just like I did for keeping track of what the on going review by you

**Comment by vidhan13j07** [comment]
Errors remaining for src/trsp/src/trsp.c: https://gist.github.com/vidhan13j07/81d27d6c0cd3c40b028a8f77c6bd63d3

Errors remaining for src/trsp/src/GraphDefinition.cpp: https://gist.github.com/vidhan13j07/068ae420753b1e0e958c2453abeda3b1

**Comment by cvvergara** [comment]
@vidhan13j07 I'll wait for merging when all the three of you finish, so that I only regenerate the developers documentation once

**Pull request merged**
