### PR TITLE
fixed issue #1917 pgr_prim_rt

### LINKED ISSUE #1917: Making compilation faster include/c_types/pgr_prim_rt.h
Refer to #1893 for instructions and details.

### PR DESCRIPTION
**Pull request by Jayita10**
Fixes #1917 

Changes proposed in this pull request:
- modified:   include/c_types/pgr_prim_rt.h
- modified:   src/spanningTree/prim_driver.cpp

@pgRouting/admins

### CODE REVIEW

**Comment by Jayita10** [comment]
Do I need to change any other file?

**Comment by cvvergara** [comment]
The execution didnt fail so I dont think so

**Review by cvvergara — APPROVED** [review]
Thanks for the contribution

**Review by cvvergara — CHANGES_REQUESTED** [review]
The PR should be done to develop branch

**Comment by cvvergara** [comment]
Sorry, its not that easy to change the branch Because you made changes to main, instead of to develop, you are carrying commits that do not belong to develop.
My suggestion is that you start over, but start working on the correct branch.
Please create another PR.

**Pull request closed without merging**
