### PR TITLE
[dijkstra] removing directive PGSQL_VERSION > 95

### LINKED ISSUE #1951: PostgreSQL 9.5 is no longer supported dijkstra
Refer to #1938 for instructions and details.

### PR DESCRIPTION
**Pull request by bkrit**
Fixes #1951

### CODE REVIEW

**Comment by cvvergara** [comment]
@bkrit you made the Pull request to the wrong branch
please modify to merge to `develop` branch

**Comment by bkrit** [comment]
@cvvergara I've made the required change, please review.

**Comment by bkrit** [comment]
@cvvergara I've made the change, please review.

**Comment by cvvergara** [comment]
@bkrit Are you participating on OSD? if that is the case I need a message on the slack channel for pgrouting-2021 that points to this Pull Request.
So that I can tag this as an OSD contribution.
If not, then this PR (and corresponding issue) will not have that OSD label

**Review by cvvergara — APPROVED** [review]

**Comment by bkrit** [comment]
> @bkrit Are you participating on OSD? if that is the case I need a message on the slack channel for pgrouting-2021 that points to this Pull Request.
> So that I can tag this as an OSD contribution.
> If not, then this PR (and corresponding issue) will not have that OSD label

Yes, I'll be participating in OSD. I request you to please share the slack url for pgrouting.

**Comment by cvvergara** [comment]
I can not do the link share for you, you have to do it. its your contribution.
When you register to the slack channel please submit the link

**Comment by cvvergara** [comment]
I can not give the slack channel, only registered people on OSD have access to it

**Pull request merged**
