### PR TITLE
fix for Issue1925 Point_on_edge_t

### LINKED ISSUE #1925: Making compilation faster  include/c_types/point_on_edge_t.h
Refer to #1893 for instructions and details.

### PR DESCRIPTION
**Pull request by Ri7Sh**
Fixes #1925

### CODE REVIEW

**Review by cvvergara — APPROVED** [review]
Thanks for the contribution

**Comment by cvvergara** [comment]
There is still a file where it needs change
https://github.com/pgRouting/pgrouting/pull/2018/checks?check_run_id=3104348203#step:8:115

**Comment by cvvergara** [comment]
Converted to draft while you fix that file

**Comment by Ri7Sh** [comment]
Closing and creating a new PR as to change the commit user. Apologies for inconvenience.

**Pull request closed without merging**
