### PR TITLE
[GSoC-2021] Experimental Function - pgr_edgeColoring 

### LINKED ISSUE #2060: GSoC'21: Detailed signature of the new function pgr_edgeColoring to be added in pgRouting
## Name of the function:

**pgr_edgeColoring()**: Edge Coloring is an algorithm used for coloring of the edges for the vertices in the graph. It is an assignment of colors to the edges of the graph so that no two adjacent edges have the same color.
It can tell us whether a graph is **Bipartite**. If in a graph, the chromatic number **χ′(G)** i.e. minimum number of colors needed for proper edge coloring of graph is equal to degree **Δ** of the graph, (i.e. **χ′(G) = Δ**) then graph is said to be Bipartite. But, the vice-versa is not always true.

### Main characteristics of the function:

- Applicable for **undirected** and **loop-free** (i.e *no self-loops and no parallel edges*) graphs.
- The graph can be either weighted or unweighted.
- At most **Δ + 1** colors are used, where **Δ** is the degree of the graph.
- The returned rows are ordered in ascending order of the edge value.
- Time complexity of the function is: `O(|E||V|)`
  - where: `|E|` is the number of edges in the graph.
  - `|V|` is the number of vertices in the graph.

### Variants:

- pgr_edgeColoring()

```sql
pgr_edgeColoring(Edges SQL)
RETURNS SET OF (edge_id, color_id)
OR EMPTY SET
```

### Parameters:

Parameter | Type | Description
-------------- | ------- | ---------------
**Edges SQL** | ``TEXT`` | Inner SQL query, as described below.

### Inner Query:

**Edges SQL**: It should be an SQL query which should return a set of rows with the following columns:

Column | Type | Default | Description
---------- | ------- | --------- | ----------------
**id** | ``ANY-INTEGER`` | | Identifier of the edge
**source** | ``ANY-INTEGER`` | | Identifier of the first end point vertex of the edge
**target** | ``ANY-INTEGER`` | | Identifier of the second end point vertex of the edge
**cost** | ``ANY-NUMERICAL`` | | Weight of the edge (source, target). When negative: edge `(source, target)` does not exist on the graph.
**reverse_cost** | ``ANY-NUMERICAL`` | -1 | Weight of the edge (target, source). When negative: edge `(target, source)` does not exist on the graph.

Where:
``ANY-INTEGER``  =  SMALLINT, INTEGER, BIGINT
``ANY-NUMERICAL``  =  SMALLINT, INTEGER, BIGINT, REAL, FLOAT

### Result Columns:

Returns SET OF ``(edge_id, color_id)``

Column | Type | Description
---------- | ------- | --------------
**edge_id** | ``BIGINT`` | Identifier of the edge.
**color_id** | ``BIGINT`` | Identifier of the color of the edge. The minimum value of color is 1.

### PR DESCRIPTION
**Pull request by veenits123**
Closes #2060

This PR adds one new pgRouting function:
- ``pgr_edgeColoring``: Returns the edge coloring of an undirected and loop-free (i.e *no self-loops and no parallel edges*) graph.

This is a final merge PR containing commits from several different PRs combined. 

The intermediate PRs made on the [GSoC-pgRouting](https://github.com/pgRouting/GSoC-pgRouting/) repository are as follows:  

| Description |  Pull Requests |
| -----------| --------------------- |
| pgr_edgeColoring | <ul><li>pgRouting/GSoC-pgRouting#169</li><li>pgRouting/GSoC-pgRouting#171</li><li>pgRouting/GSoC-pgRouting#173</li><li>pgRouting/GSoC-pgRouting#176</li><li>pgRouting/GSoC-pgRouting#179</li><li>pgRouting/GSoC-pgRouting#182</li><li>pgRouting/GSoC-pgRouting#184</li><li>pgRouting/GSoC-pgRouting#186</li><li>pgRouting/GSoC-pgRouting#188</li></ul> |

### CODE REVIEW

**Review by dkastl — APPROVED** [review]
Great, @veenits123 !
Congratulations to adding a new function to pgRouting!

**Comment by veenits123** [comment]
Thanks, @dkastl !
Will love to add more functionality to pgRouting in the coming future.

**Review by cvvergara — APPROVED** [review]

**Review by rahulworld — APPROVED** [review]
Great @veenits123 
LGTM
Your code is very structured with comments. 
Congratulation Your code is adding a new function to pgRouting! 
Thanks

**Comment by cvvergara** [comment]
@veenits123 Thanks for your contribution.
As this is the last week and I've been following carefully your work,
I am giving you the go ahead to make the rebase & merge

**Review by omshinde — APPROVED** [review]
Congratulations @veenits123 ! Great job!

**Review by robe2 — APPROVED** [review]

**Review by cayetanobv — APPROVED** [review]

**Pull request merged**
