### PR TITLE
deprecate pgr_gsoc_vrppdtw in favor of pgr_pickDeliver

### PR DESCRIPTION
**Pull request by cvvergara**
* Deprecate experimental function `pgr_gsoc_vrppdtw`
  * documentation: https://docs.pgrouting.org/pickDeliver/en/pgr_gsoc_vrppdtw.html
* New experimental function `pgr_pickDeliver` & `pgr_pickDeliverEuclidean`
  * tentative documentation: https://docs.pgrouting.org/pickDeliver/en/pgr_pickDeliver.html
  * tentative documentation: https://docs.pgrouting.org/pickDeliver/en/pgr_pickDeliverEuclidean.html
    (the link will no longer exist after this PR is merged and 'dev' documentation is updated)

Current tentative names:
*  `pgr_pickDeliver` & `pgr_pickDeliverEuclidean` 
can be
*  `pgr_pickDrop` & `pgr_pickDropEuclidean` (Pick up & Drop off)

In general Tasks done are:

* Updating directories to be processed
    modified:   configuration.conf
* Setting the new functions
    modified:   sql/pickDeliver/pickDeliver.sql
    modified:   sql/pickDeliver/pickDeliverEuclidean.sql
    modified:   doc/pickDeliver/VRP-category.rst
* Sending to legacy deprecated function
    renamed:    sql/vrppdtw/_gsoc_vrppdtw.sql -> sql/legacy/vrppdtw/_gsoc_vrppdtw.sql
    renamed:    sql/vrppdtw/gsoc_vrppdtw.sql -> sql/legacy/vrppdtw/gsoc_vrppdtw.sql
* Preparing documentation of new functions
    modified:   doc/pickDeliver/pgr_pickDeliver.rst
    modified:   doc/pickDeliver/pgr_pickDeliverEuclidean.rst
    modified:   doc/queries/CMakeLists.txt
* Updating the contents and the release notes
    modified:   doc/src/proposed.rst
    modified:   doc/src/release_notes.rst
	modified:   NEWS
* Removing documentation of deprecated function
    deleted:    doc/queries/doc-gsoc_vrppdtw.queries
    deleted:    doc/vrppdtw/CMakeLists.txt
    deleted:    doc/vrppdtw/pgr_gsoc_vrppdtw.rst
    deleted:    locale/de/LC_MESSAGES/pgr_gsoc_vrppdtw.po
    deleted:    locale/en/LC_MESSAGES/pgr_gsoc_vrppdtw.po
    deleted:    locale/es/LC_MESSAGES/pgr_gsoc_vrppdtw.po
    deleted:    locale/fr/LC_MESSAGES/pgr_gsoc_vrppdtw.po
    deleted:    locale/it/LC_MESSAGES/pgr_gsoc_vrppdtw.po
    deleted:    locale/ja/LC_MESSAGES/pgr_gsoc_vrppdtw.po
    deleted:    locale/pot/pgr_gsoc_vrppdtw.pot
    deleted:    locale/ru/LC_MESSAGES/pgr_gsoc_vrppdtw.po
* Removing tests for vrppdtw
    deleted:    pgtap/vrppdtw/no_crash_test-vrppdtw.sql
    deleted:    sql/vrppdtw/CMakeLists.txt
    deleted:    test/vrppdtw/doc-gsoc_vrppdtw.result
    deleted:    test/vrppdtw/doc-gsoc_vrppdtw.test.sql
    deleted:    test/vrppdtw/test.conf
* updating signature file
    modified:   sql/sigs/pgrouting--3.0.0.sig

@pgRouting/admins

### CODE REVIEW

**Comment by cvvergara** [comment]
Please vote here (with thumbs up) for

 `pgr_pickDeliver` & pgr_pickDeliverEuclidean`

**Comment by cvvergara** [comment]
Please vote here (with thumbs up) for

 `pgr_pickDrop` & pgr_pickDropEuclidean`

**Comment by robe2** [comment]
I'm against Drop because it sounds too much like Drop function so people might think it's for destroying something.

**Comment by woodbri** [comment]
Make self documenting with full name like pgr_pickUpDropOffEuclidean.

**Comment by dkastl** [comment]
I agree with @robe2 and I'm also thinking, if there is another name as @woodbri suggests, just without too many upper cases in the name ;-)

What about:
- `pgr_pickupDropoff`
- `pgr_pickupDropoffEuclidean`

**Comment by manikanta-kondeti** [comment]
- pgr_pickupDropoff
   - pgr_pickupDropoffEuclidean

Sounds good +1

**Comment by dkastl** [comment]
Actually the title of this PR is probably wrong: it says `vpr_pickDeliver` and should be `pgr_` prefix, right?

**Comment by cvvergara** [comment]
Thanks for voting

**Pull request merged**
