### PR TITLE
[GSoC-2022] Experimental Function - cuthillMckeeOrdering

### PR DESCRIPTION
**Pull request by shobhit162**
This PR adds one new pgRouting function:
- ``cuthillMckeeOrdering``: Returns the reverse Cuthill-Mckee Ordering of the vertices in the undirected graph.

This is a final merge PR containing commits from several different PRs combined.

The intermediate PRs made on the [GSoC-pgRouting](https://github.com/pgRouting/GSoC-pgRouting/) repository are as follows:

| Description |  Pull Requests |
| -----------| --------------------- |
| cuthillMckeeOrdering | <ul><li>pgRouting/GSoC-pgRouting#216</li><li>pgRouting/GSoC-pgRouting#220</li><li>pgRouting/GSoC-pgRouting#222</li><li>pgRouting/GSoC-pgRouting#226</li><li>pgRouting/GSoC-pgRouting#232</li><li>pgRouting/GSoC-pgRouting#234</li><li>pgRouting/GSoC-pgRouting#244</li><li>pgRouting/GSoC-pgRouting#249</li><li>pgRouting/GSoC-pgRouting#250</li><li>pgRouting/GSoC-pgRouting#254</li><li>pgRouting/GSoC-pgRouting#255</li><li>pgRouting/GSoC-pgRouting#258</li></ul> |

### CODE REVIEW

**Review by cvvergara — APPROVED** [review]

**Review by krashish8 — APPROVED** [review]
Thanks @shobhit162 for your contribution!
Looks good overall! 🎉

**Comment by cvvergara** [comment]
The fail is on the translation, that will be fixed afterwards

**Review by omshinde — APPROVED** [review]
Thanks for your contributions, Shobhit! :)

**Review by cayetanobv — APPROVED** [review]

**Comment by shobhit162** [comment]
#2367

**Pull request merged**
