### PR TITLE
fix for Issue1926 Restriction_t 

### LINKED ISSUE #1926: Making compilation faster include/c_types/restriction_t.h
Refer to #1893 for instructions and details.

### PR DESCRIPTION
**Pull request by ManasviGoyal**
Fixes #1926 

Changes proposed in this pull request:

-changes to restriction_t.h
-adjusting code based on changes on structure Restriction_t

@pgRouting/admins

### CODE REVIEW

**Comment by ManasviGoyal** [comment]
@cvvergara pls check

**Comment by cvvergara** [comment]
There are compilation errors that need to be fixed for example:
https://github.com/pgRouting/pgrouting/pull/2029/checks?check_run_id=3116542476#step:8:79
in file `src/trsp/trsp.c` also add the line `#include "c_types/restriction_t.h"`

**Comment by ManasviGoyal** [comment]
@cvvergara able to do fixup. now pls tell what to do to fix the buid issues?

**Comment by cvvergara** [comment]
@ManasviGoyal 
in #1893  There is a section "The compiler is your best friend". Please read it carefully.
Developers compile locally on their computer. 

But lets use the actions like I used it to pointed out a change you should have done.
You need to learn to figure out what is the next change, we will use the actions (as I can not see your computer's compilation):

- Click on a "details" of a test that did not pass. (We are simulating here that the compilation is taking place locally)
- And give me a link similar to what I gave you when I pointed out a change you needed to do. (we are simulating here that you show me where the compiler complains)
- Based on the instructions in #1893, and the contents of the link, post here what you think you should do.

**Comment by ManasviGoyal** [comment]
@cvvergara 
add `#include "c_types/restriction_t.h"` in
`src/trsp/CMakeFiles/trsp.dir/trsp.c`
`src/trsp/CMakeFiles/trsp.dir/new_trsp.c`

**Comment by ManasviGoyal** [comment]
> There are compilation errors that need to be fixed for example:
> https://github.com/pgRouting/pgrouting/pull/2029/checks?check_run_id=3116542476#step:8:79
> in file `src/trsp/trsp.c` also add the line `#include "c_types/restriction_t.h"`

sir i did this but it is showing build erroe

> There are compilation errors that need to be fixed for example:
> https://github.com/pgRouting/pgrouting/pull/2029/checks?check_run_id=3116542476#step:8:79
> in file `src/trsp/trsp.c` also add the line `#include "c_types/restriction_t.h"`

image
should i add restrict instead of restriction?

**Comment by ManasviGoyal** [comment]
@cvvergara 
Pls tell how can I fix it

**Comment by cvvergara** [comment]
From the screenshot I can deduce that the problem is in this file `include/drivers/trsp/trsp_driver.h` is an `.h` file
From the "File changes" tab that file has not been modified
From the Instructions, this line needs to be added
```
typedef struct Restriction_t Restriction_t;
```

**Comment by cvvergara** [comment]
Your changes did not work.
Will close this PR.

**Pull request closed without merging**
