### PR TITLE
[c_type] fixing pgr_mst_rt

### LINKED ISSUE #1915: Making compilation faster include/c_types/pgr_mst_rt.h
Refer to #1893 for instructions and details.

### PR DESCRIPTION
**Pull request by Jayita10**
Fixes #1915

Changes proposed in this pull request:
- modified: include/c_types/pgr_mst_rt.h
- modified: src/spanningTree/mst_common.cpp

@pgRouting/admins

### CODE REVIEW

**Comment by Jayita10** [comment]
Please review @cvvergara

**Comment by cvvergara** [comment]
It is noticeable that you are using the web to modify the files, that is not the way a developer works.
Please read carefully the instructions on #1893 

That been said, if you work on the web, you then need to use the actions to detect what is wrong.
Click on "Details" of a failing run and look for what is wrong for example:
https://github.com/pgRouting/pgrouting/pull/2034/checks?check_run_id=3177551053#step:8:171
Which means that the problem is on `include/drivers/spanningTree/kruskal_driver.h` which is an .h file, and then you follow the instructions where you add:
```
typedef struct pgr_mst_rt pgr_mst_rt;
```
commit and wait to see what the actions say after the change. 
and do it over and over until things are ok.

I will mark as draft, please click on "Ready for review" when the actions pass

**Review by cvvergara — CHANGES_REQUESTED** [review]
Please see the comment about the changes that need to be done

**Comment by cvvergara** [comment]
No progress or comment on this PR. 
Closing

**Pull request closed without merging**
