### PR TITLE
Dd develop, comparing for travis test

### PR DESCRIPTION
**Pull request by cvvergara**
I want to see if it passes travis test

### CODE REVIEW

**Comment by cvvergara** [comment]
Not working

**Comment by dkastl** [comment]
You need to enable your branch for Travis CI tests: 
https://github.com/pgRouting/pgrouting/blob/develop/.travis.yml#L17-L21

**Comment by woodbri** [comment]
@dkastl I have reconfigured the travis matrix and disabled all the postgis 1.5 versions and building with template databases. I also added support for postgresql 9.4. I think I currently have everything working against branch develop_2_1_0 except most of the tests seem to be hanging on test ksp_v3, so @cvvergara  needs to look into that. She is developing on pg 9.4 and it happens to work there.

**Comment by woodbri** [comment]
I also think we can probably simplify the pgrouting_install.sh to install postgis just from the package manager rather than from source. We only need to support postgis 2.0, 2.1, 2.2? going forward.

**Comment by dkastl** [comment]
Thanks for the updates! It was pretty old.

I think there was a reason why I had to build PostGIS from source, but I don't remember the reason. Maybe there were just no packages available. So using packages is of course better, if they exist.

**Comment by woodbri** [comment]
if you have a chance, you might want to review and update the scripts. I only made the minimal changes to get is running for @cvvergara 

This might be of interest:
http://docs.travis-ci.com/user/using-postgresql/#Selecting-a-PostgreSQL-Version

I also think we need to update the release matrix we plan for 2.1.0 and 3.x regarding postgresql, postgis, and C++ compiler version requirements.

The later is of interest because OSRM is only supporting C++11 and there was some thought of pulling in the shared memory connection code but that would probably get done in a separate extension like osrm-tools. But some of the code the @cvvergara has be writing also requires C++11 and if we want any of that to go into 2.1.x we would need to add that requirement to the release or backport all the C++11-isms to C++98 which would be a pain or delay releasing them until 3.0.0.

**Comment by cvvergara** [comment]
@dkastl 
Need to change git tag so I can fix pgr_version results to match the tag we are going to use
(re-opening to make travis comments on this issue)

**Comment by cvvergara** [comment]
Decided to close because we are not merging, but I see we can still coment here.

**Pull request closed without merging**
