### PR TITLE
Experimental pgr_dijkstraNear pgr_dijkstraNearCost

### LINKED ISSUE #1615: pgr_dijkstraNear & pgr_dijkstraNearCost
**Is your feature request related to a problem? Please describe.**
```
pgr_dijkstraNear(Edges SQL, Start vid,  End vids  [, directed] [, cap])
pgr_dijkstraNear(Edges SQL, Start vids, End vid   [, directed] [, cap])
pgr_dijkstraNear(Edges SQL, Start vids, End vids  [, directed] [, cap]. [global])
pgr_dijkstraNear(Edges SQL, Combinations SQL  [, directed] [, cap], [global])
RETURNS SET OF (seq, path_seq, start_vid, end_vid, node, edge, cost, agg_cost)
OR EMPTY SET
```
```
pgr_dijkstraNearCost(Edges SQL, Start vid,  End vids  [, directed] [, cap])
pgr_dijkstraNearCost(Edges SQL, Start vids, End vid   [, directed] [, cap])
pgr_dijkstraNearCost(Edges SQL, Start vids, End vids  [, directed] [, cap]. [global])
pgr_dijkstraNearCost(Edges SQL, Combinations SQL  [, directed] [, cap], [global])
RETURNS SET OF (start_vid, end_vid, agg_cost)
OR EMPTY SET
```
**Describe the solution you'd like**

Suppose subway stations are at vertices 3,6,7
Problem 1 Find the closest station traveling **from** vertex 2  to a station when traveling on a car
```
SELECT * FROM pgr_dijkstraNear(
    'SELECT id, source, target, cost, reverse_cost FROM edge_table',
    2, ARRAY[3, 6, 7],
    directed => true   -- like all other ones its the default
);
 seq | path_seq | start_vid | end_vid | node | edge | cost | agg_cost
-----+----------+-----------+---------+------+------+------+----------
   1 |        1 |         2 |       6 |    2 |    4 |    1 |        0
   2 |        2 |         2 |       6 |    5 |    8 |    1 |        1
   3 |        3 |         2 |       6 |    6 |   -1 |    0 |        2
(3 rows)
```

Problem 1 Find the closest 2 stations traveling **to** vertex 2  from a station when traveling on a car
```
SELECT * FROM pgr_dijkstraNear(
    'SELECT id, source, target, cost, reverse_cost FROM edge_table',
    ARRAY[3, 6, 7], 2,
    true,
    cap => 2    -- cap default is 1 like in problem 1
);
 seq | path_seq | start_vid | end_vid | node | edge | cost | agg_cost
-----+----------+-----------+---------+------+------+------+----------
   1 |        1 |         3 |       2 |    3 |    2 |    1 |        0
   2 |        2 |         3 |       2 |    2 |   -1 |    0 |        1
   3 |        1 |         6 |       2 |    6 |    8 |    1 |        0
   4 |        2 |         6 |       2 |    5 |    4 |    1 |        1
   5 |        3 |         6 |       2 |    2 |   -1 |    0 |        2
(5 rows)
```
Problem 3: Find the best pedestrian connection between two subway lines
```
SELECT * FROM pgr_dijkstraNear(
    'SELECT id, source, target, cost, reverse_cost FROM edge_table',
    ARRAY[4, 9], ARRAY[3, 6, 7],
    directed => false   -- undirected, and cap gets the default 1, global default true
);
 seq | path_seq | start_vid | end_vid | node | edge | cost | agg_cost
-----+----------+-----------+---------+------+------+------+----------
   1 |        1 |         4 |       3 |    4 |    3 |    1 |        0
   2 |        2 |         4 |       3 |    3 |   -1 |    0 |        1
(2 rows)
```

Problem 4: Find the nearest station’s paths between two subway lines for a directed graph when using a car
```
SELECT * FROM pgr_dijkstraNear(
    'SELECT id, source, target, cost, reverse_cost FROM edge_table',
    'SELECT unnest(ARRAY[3, 6, 7]) as source, target FROM (SELECT unnest(ARRAY[4, 9]) AS target) a
    UNION
    SELECT unnest(ARRAY[4, 9]), target FROM (SELECT unnest(ARRAY[3, 6, 7]) AS target) b',
    true,  -- undirected -- cap default = 1
    global => false  -- global default is true, which will give only one route, but with false would give one route per source
);
 seq | path_seq | start_vid | end_vid | node | edge | cost | agg_cost
-----+----------+-----------+---------+------+------+------+----------
   1 |        1 |         4 |       3 |    4 |    3 |    1 |        0
   2 |        2 |         4 |       3 |    3 |   -1 |    0 |        1
   3 |        1 |         6 |       9 |    6 |    9 |    1 |        0
   4 |        2 |         6 |       9 |    9 |   -1 |    0 |        1
   5 |        1 |         9 |       6 |    9 |    9 |    1 |        0
   6 |        2 |         9 |       6 |    6 |   -1 |    0 |        1
   7 |        1 |         3 |       9 |    3 |    5 |    1 |        0
   8 |        2 |         3 |       9 |    6 |    9 |    1 |        1
   9 |        3 |         3 |       9 |    9 |   -1 |    0 |        2
  10 |        1 |         7 |       9 |    7 |    6 |    1 |        0
  11 |        2 |         7 |       9 |    8 |    7 |    1 |        1
  12 |        3 |         7 |       9 |    5 |    8 |    1 |        2
  13 |        4 |         7 |       9 |    6 |    9 |    1 |        3
  14 |        5 |         7 |       9 |    9 |   -1 |    0 |        4
(14 rows)
```
The Cost Versions would work similar but return the (start_vid, end_vid, agg_cost) 

**Describe alternatives you've considered**
none

### PR DESCRIPTION
**Pull request by cvvergara**
Fixes #1615

Changes proposed in this pull request:
Adding 2 new experimental functions `pgr_dijkstraNear` and `pgr_dijkstraNearCost`
- the pgtap tests of how it is intended to work
- changes to de code
- the documentation

@pgRouting/admins

### CODE REVIEW

**Review by omshinde — APPROVED** [review]
Thanks for the update!

**Comment by cvvergara** [comment]
Thanks for the approval, converted to draft because of the timing message is not correct

```
DEBUG:  directed 1 only_cost 0 normal 1 n_goals 1
DEBUG:  id 20
DEBUG:  source 20
DEBUG:  target 20
DEBUG:  cost 701
DEBUG:  reverse_cost 701
DEBUG:  Reading 18 edges
DEBUG:  Elapsed time for reading edges:
 0.000113 sec = (39990.000000 - 39877.000000) / CLOCKS_PER_SEC 
DEBUG:  Array size 1
DEBUG:  Elapsed time for reading Array:
 0.000006 sec = (40008.000000 - 40002.000000) / CLOCKS_PER_SEC 
DEBUG:  Array size 3
DEBUG:  Elapsed time for reading Array:
 0.000003 sec = (40016.000000 - 40013.000000) / CLOCKS_PER_SEC 
DEBUG:  Starting timer
DEBUG:  Elapsed time for processing pgr_dijkstra:    <------------------ HERE
 0.000372 sec = (40395.000000 - 40023.000000) / CLOCKS_PER_SEC 
DEBUG:  Inserting vertices into a c++ vector structure
Working with directed Graph
Converting a set of paths into the tuples
LOG:  duration: 0.910 ms  statement: SELECT * FROM pgr_dijkstraNear(
    'SELECT id, source, target, cost, reverse_cost FROM edge_table',
    2, ARRAY[3, 6, 7],
    directed => true   
);
```

**Comment by cvvergara** [comment]
Also there is a log of "garbage on that debug", like
```
DEBUG:  directed 1 only_cost 0 normal 1 n_goals 1
DEBUG:  id 20
DEBUG:  source 20
DEBUG:  target 20
DEBUG:  cost 701
DEBUG:  reverse_cost 701
DEBUG:  Reading 18 edges
DEBUG:  Elapsed time for reading edges:
```

**Comment by cvvergara** [comment]
Debug messages come out nicer
```
SELECT * FROM pgr_dijkstraNear(
    'SELECT id, source, target, cost, reverse_cost FROM edge_table',
    2, ARRAY[3, 6, 7],
    directed => true   -- like all other ones its the default
);
DEBUG:  Elapsed time for reading edges: 0.000078 sec = (31118.000000 - 31040.000000) / CLOCKS_PER_SEC 
DEBUG:  Elapsed time for reading Array: 0.000003 sec = (31149.000000 - 31146.000000) / CLOCKS_PER_SEC 
DEBUG:  Elapsed time for reading Array: 0.000002 sec = (31167.000000 - 31165.000000) / CLOCKS_PER_SEC 
DEBUG:  Elapsed time for processing pgr_dijkstraNear: 0.000366 sec = (31547.000000 - 31181.000000) / CLOCKS_PER_SEC 
LOG:  duration: 1.192 ms  statement: SELECT * FROM pgr_dijkstraNear(
    'SELECT id, source, target, cost, reverse_cost FROM edge_table',
    2, ARRAY[3, 6, 7],
    directed => true   
);
 seq | path_seq | start_vid | end_vid | node | edge | cost | agg_cost 
-----+----------+-----------+---------+------+------+------+----------
   1 |        1 |         2 |       6 |    2 |    4 |    1 |        0
   2 |        2 |         2 |       6 |    5 |    8 |    1 |        1
   3 |        3 |         2 |       6 |    6 |   -1 |    0 |        2
(3 rows)
```

**Review by robe2 — APPROVED** [review]

**Review by prakashupes — APPROVED** [review]

**Pull request merged**
