### PR TITLE
[GSoC 2023] Modifying  drivingdistance

### PR DESCRIPTION
**Pull request by aryan1010**
This PR modifies one existing function:

- ``pgr_drivingdistance`: 
  - Adding one new result column 'depth'.
  - Normalizing the output(Adding start_vid column for single vertex).

This is a final merge PR containing commits from several different PRs combined.

The intermediate PRs made on the [GSoC-pgRouting](https://github.com/pgRouting/GSoC-pgRouting/) repository are as follows:

| Description |  Pull Requests |
| -----------| --------------------- |
| pgr_drivingdistance| <ul><li>pgRouting/GSoC-pgRouting#293</li><li>pgRouting/GSoC-pgRouting#296</li><li>pgRouting/GSoC-pgRouting#305</li><li>pgRouting/GSoC-pgRouting#310</li><li>pgRouting/GSoC-pgRouting#311</li><li>pgRouting/GSoC-pgRouting#315</li><li>pgRouting/GSoC-pgRouting#321</li><li>pgRouting/GSoC-pgRouting#329</li><li>pgRouting/GSoC-pgRouting#331</li><li>pgRouting/GSoC-pgRouting#334</li><li>pgRouting/GSoC-pgRouting#338</li><li>pgRouting/GSoC-pgRouting#344</li></ul> |

The wiki page with more details on this project can be found [here](https://github.com/pgRouting/pgrouting/wiki/GSoC-2023-Implementing-Dijkstra%E2%80%99s-Driving-distance-Function-and-its-migration).

### CODE REVIEW

**Comment by krashish8** [comment]
Please also update the `NEWS` and `release_notes.rst` file, similar to the other GSoC PRs.

**Review by robe2 — CHANGES_REQUESTED** [review]
Looks okay aside from the missing news that @krashish8 mentioned.

**Comment by aryan1010** [comment]
@robe2 @krashish8  i have updated news and release_notes but it is failing new check now

**Comment by krashish8** [comment]
You don't have to update NEWS manually. Use this script to generate NEWS: tools/release-scripts/notes2news.pl

**Review by krashish8 — APPROVED** [review]
Links are written in a different format in rst file: https://sublime-and-sphinx-guide.readthedocs.io/en/latest/references.html#links-to-external-web-pages

I think @Aniket-debug also needs to fix this in the release notes.
Otherwise, this looks good. 🎉

**Review by robe2 — APPROVED** [review]

**Comment by robe2** [comment]
> Links are written in a different format in rst file: https://sublime-and-sphinx-guide.readthedocs.io/en/latest/references.html#links-to-external-web-pages
> 
> I think @Aniket-debug also needs to fix this in the release notes. Otherwise, this looks good. 🎉

I think @squarege made this mistake too.  I'll go ahead and merge this for expediency.

**Pull request merged**
