### PR TITLE
Reducing file size

### PR DESCRIPTION
**Pull request by pratamjain**
Fixes # .

Changes proposed in this pull request:
-
-
-

@pgRouting/admins

### CODE REVIEW

**Comment by cvvergara** [comment]
You are failing to describe the nature of your change on the comment of the pull request

**Comment by cvvergara** [comment]
There is no related issue for this PR
- What are you trying to accomplish by deleting 2 blank lines?
- Why do you think the repository size will be drastically reduced by removing 2 "\n" characters from one file?

**Review by dkastl — CHANGES_REQUESTED** [review]
Reducing file size by removing blank lines akes no sense. The only thing you save here is a line break, but things get much harder to read.

@pratamjain , what's the purpse of these pull requests?
For Hacktoberfest you are late, and for GSoC you better look for something more useful please.

**Comment by pratamjain** [comment]
> Reducing file size by removing blank lines makes no sense. The only thing you save here is a line break, but things get much harder to read.
> 
> @pratamjain , what's the purpse of these pull requests?
> For Hacktoberfest you are late, and for GSoC you better look for something more useful please.

Sure sir . Sorry for the inconvenience

**Comment by pratamjain** [comment]
Sorry for the inconvenience , will try & contribute more useless things

**Pull request closed without merging**
