### PR TITLE
Fix issue 1733 pgr_bdAstar

### LINKED ISSUE #1733: pgr_bdAstar fails when source or target vertex does not exist in the graph
**Describe the bug**
The `pgr_bdAstar` function fails (`AssertFailedException`) when either the source vertex, or the target vertex, or both do not exist in the graph.

**To Reproduce**

Execute the following query:
```sql
SELECT * FROM pgr_bdAstar(
    'SELECT id, source, target, cost, reverse_cost, x1, y1, x2, y2
    FROM edge_table',
    2, 100
);
```

Here vertex with id `100` does not exist in the graph. This query gives the error:
```
ERROR:  AssertFailedException: has_vertex(vid) at ... include/cpp_common/pgr_base_graph.hpp:527
```

**Expected behavior**
This query is expected to return an empty set of rows:

```sql
SELECT * FROM pgr_bdAstar(
    'SELECT id, source, target, cost, reverse_cost, x1, y1, x2, y2
    FROM edge_table',
    2, 100
);
```
```
 seq | path_seq | node | edge | cost | agg_cost 
-----+----------+------+------+------+----------
(0 rows)
```

**Specifications (please complete the following information):**
Use the commands:
```
sampledata=# SELECT version();
                                                            version                                                            
-------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 12.4 (Ubuntu 12.4-0ubuntu0.20.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0, 64-bit
(1 row)

sampledata=# SELECT postgis_full_version();
                                                                        postgis_full_version                                                                        
--------------------------------------------------------------------------------------------------------------------------------------------------------------------
 POSTGIS="3.0.0 r17983" [EXTENSION] PGSQL="120" GEOS="3.8.0-CAPI-1.13.1 " PROJ="6.3.1" LIBXML="2.9.4" LIBJSON="0.13.1" LIBPROTOBUF="1.3.3" WAGYU="0.4.3 (Internal)"
(1 row)

sampledata=# SELECT pgr_version();
 pgr_version 
-------------
3.2.0-dev
(1 row)

```

### PR DESCRIPTION
**Pull request by krashish8**
Fixes #1733 

Changes proposed in this pull request:
- [x] Added pgTAP tests
- [x] Fix issue

@pgRouting/admins

### CODE REVIEW

**Comment by dkastl** [comment]
Thanks! Is the empty result also what other functions return in this case?
I'm just asking, because the alternative might be an understandable error message.

Assuming we return an empty result it looks like there is no route, but we don't know this is because of a missing stop point, which is more of an error, while having no route between two existing points is a correct result.

That said, if all other functions handle the exception like this, then let's do it the same for this one.
In that case we can discuss the case and eventually make a coordinated change for another release.

**Comment by krashish8** [comment]
Yes, the other functions also return an empty result in this case.
But, the idea of an understandable error message seems good to me.

**Comment by dkastl** [comment]
OK, that makes totally sense then.
We should probably keep track of that idea to change it to an error everywhere ... @cvvergara , what do you think about it? Is there a particular reason to return an empty result if source or destination are missing?

**Review by dkastl — APPROVED** [review]
Looks good to me!

**Comment by cvvergara** [comment]
Well, actually the graphs are formed as:
G=(E,V) 
the edges are deduced from the edges table
the vertices are deduced from the edges table and from the input parameters.
Internally for example the one to one is transformed to be a many to many, if we throw an exeption when a path is not found, when a real many to many  finds a no path, will wont be throwing an exception because other paths can be found.
So its better to return EMPTY SET as documented on the functions documentation

**Review by cvvergara — APPROVED** [review]

**Comment by cvvergara** [comment]
@krashish8 
Thanks for the update, you can rebase & merge

**Comment by cvvergara** [comment]
Will port this fix to master and release-3.0

**Pull request merged**
